### ISSUE TITLE
Error exporting gcode

### ISSUE THREAD

**Issue by XabierV** [sn4k3/Ender3#1]
Using printer Creality Ender3 - Stock, filament Generic PLA, and print 0.20mm Normal Ender3 with Slic3rPE 1.39.0, with 3DBenchy STL. Slice process completes correctly, but fails to export the gcode file, with the following error message:

!!!!! Failed to process the custom G-code template end_gcode
Parsing error at line 9: Not a variable name
{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up
    ^
!!!!! End of an error report for the custom G-code template end_gcode

I'm a total newbie with 3D printing and slicing, but it looks as the variable layer_z is not being initialized...

[3DBenchy_PLA0.2mm.gcode.txt](https://github.com/sn4k3/Ender3/files/2673063/3DBenchy_PLA0.2mm.gcode.txt)

**Comment by sn4k3** [comment]
You need to download the new Slic3r PE, the 1.39 don't have that option... Please update
