### ISSUE TITLE
Under/no extrusion while after priming phase

### ISSUE THREAD

**Issue by NovaViper** [sn4k3/Ender3#11]
For some strange reason, I notice that the printer doesn't seem to be extruding at all, which has been causing me **lots** of headache trying to figure out why.

**Comment by sn4k3** [comment]
Which printer profile are you using?
Can you try manual extrusion via printer menu and see if it extrudes at all?

**Comment by NovaViper** [comment]
I think it's my e-steps not being calibrated. I'm going to go and try to calibrate them sometime Friday and *hopefully* get the issue fixed

**Comment by sn4k3** [comment]
I had that problem before and was e-steps
