### ISSUE TITLE
Infilll and Solid Infill and Max speeds for 0.2 print profile (stock) is way too high for certain filaments

### ISSUE THREAD

**Issue by NovaViper** [sn4k3/Ender3#16]
Hi there! I wanted to report an issue relating with the Infill/Solid Infill and Max speeds for the stock 0.2 print normal profile. For some odd reason, they're set REALLY high (80 for the infills and 90 for the max speed to be extact) while every other profile is set between 50-71. For certain filaments (PETG in my case) this is *way* too fast for the infill to handle and it will immediately get ripped off the model and make basically large gashes in the model (which inventibly causes print failures). 

Currently, I've set those settings all to 56 and that seemed to have fix my troubles. I haven't tried out the high speed on PLA but it's definitely way too much for PETG to handle

**Comment by sn4k3** [comment]
Hello, Speeds are based on MVS, for 0.2mm profile the 80mm/s seens ok for normal PETG (80*0,2*0,45
= 7,2mm^3/s) While PETG is cap at 8mm^3/s on filament tab, so is under the PETG limit.
Now it can depend on temperature and filament you using, can you post your filament brand/name and temperatures you using? Also the motor and gear can influence max MVS. 

Instead of mess with speed which affect all other filaments, you can clone PETG filament and set "Max Volumetric Speed" to a lower value, and speed will ajust according.

**Comment by NovaViper** [comment]
I tried with ColorMe3D Blacker Black and Haze Purple, and Amazon Basics Purple. All running at 235C for the hotend and 75C for the bed

**Comment by sn4k3** [comment]
That's strange, 56mm/s seens low for infills given that profile, i renember i had no problem with Prusa PET when i have stock, now i can't test anymore since no longet stock.
Do you have lastest master profile? Because i updated machine limits which were in crazy numbers

**Comment by NovaViper** [comment]
Oh! So it seems I do have an older version of the master profile. I'm updating my settings now :)

**Comment by sn4k3** [comment]
> Oh! So it seems I do have an older version of the master profile. I'm updating my settings now :)

Update it and report back

**Comment by NovaViper** [comment]
I just got new profile settings added and I did decrease the volumetic speed to 7, though I still have some blobbing.. I'm going to go and switch out my nozzle (I have a 0.5 nozzle installed) and see if that's what is causing the issue

**Comment by sn4k3** [comment]
Wait you have 0.5mm nozzle in but using the 0.4 profiles?

**Comment by NovaViper** [comment]
Yeah, I had to restort to switching it because I kept having issues printing 0.32 layer heights with my 0.4 nozzle

**Comment by sn4k3** [comment]
You can't use 0.4mm profiles with a 0.5mm nozzle, there are change that must be done, including on printer tab...

but 0.4mm nozzle can do 0.32mm layers, the problem you have maybe related to other thing (If speed down doesnt help)

**Comment by NovaViper** [comment]
For some reason after that first layer, it started failing again once I went back to my 0.4 nozzle. The filament settings was all stock (except for my temps) .-.

**Comment by NovaViper** [comment]
![image](https://user-images.githubusercontent.com/7191115/62971247-f609d000-bdd6-11e9-8f41-327f6cd7d3b6.png)

**Comment by sn4k3** [comment]
Look likes more a height problem than speed. Does your extruder click?
Try put 5 at volumetric speed under filament tab

**Comment by sn4k3** [comment]
Use 40x40 square tests to speed up tests

**Comment by NovaViper** [comment]
I didn't hear the extruder clicking, and whenever it prints perimeters and walls, it doesn't have the issue shown. Im currently releveling the bed just in case it's off from my last print in PLA

**Comment by NovaViper** [comment]
Ok.. so I got a 50x50x1.28 mm rectangle going.. and it seems to be much better at 5mm^3/s

**Comment by sn4k3** [comment]
IF better but not perfect try lower, like 4

**Comment by NovaViper** [comment]
Welp, it did this in the end 
![image](https://user-images.githubusercontent.com/7191115/62974125-218fb900-bddd-11e9-8a66-eab4f4f62978.png)

**Comment by NovaViper** [comment]
But all the other layers were fine (but I didn't catch the final or the one before it to thoroughly confirm it)

**Comment by NovaViper** [comment]
I can confirm that it did indeed do that in the very top layer
![image](https://user-images.githubusercontent.com/7191115/62974421-cf02cc80-bddd-11e9-9160-c9599a9f2a68.png)

**Comment by NovaViper** [comment]
There was some issues in the layer right under it to.. it looks like at one particular spot it didn't stick properly
![image](https://user-images.githubusercontent.com/7191115/62975066-22c1e580-bddf-11e9-9fad-1dcb666ca9e6.png)

**Comment by NovaViper** [comment]
*Sigh* The 4mm^3/s top layer had issues, no layer had issues 
![image](https://user-images.githubusercontent.com/7191115/62975407-e6db5000-bddf-11e9-9569-d7bd72a71d71.png)
![image](https://user-images.githubusercontent.com/7191115/62975423-eba00400-bddf-11e9-966d-3c61368d310e.png)

**Comment by sn4k3** [comment]
Well set MVS to 1 (lower than TPU xD) if you still have problem is not related to speed.

**Comment by NovaViper** [comment]
Should I turn off the cooling fan entirely? The cooling fan seems to kick on at the very last layer

**Comment by sn4k3** [comment]
> Should I turn off the cooling fan entirely? The cooling fan seems to kick on at the very last layer

You can try, but i guess not the fan causing the problem

**Comment by NovaViper** [comment]
I just started the print at 1VMS and no fan for the PETG. I'll try the PLA one afterward

**Comment by NovaViper** [comment]
This time at 1 MVS and the fan off,it came out *perfect*

**Comment by sn4k3** [comment]
If MVS value is respected that mean +/- 7mm/s speed. Can you confirm that is that slow?
Now you can reenable fan as it was

**Comment by NovaViper** [comment]
It came out *really* slow.. took an entire hour to finish the print instead of 15 minutes

**Comment by NovaViper** [comment]
![image](https://user-images.githubusercontent.com/7191115/62979539-bac4cc80-bde9-11e9-816c-737ee9af0679.png)

**Comment by sn4k3** [comment]
Can you try now with PLA?

**Comment by NovaViper** [comment]
Alrighty. im starting the PLA print now

**Comment by NovaViper** [comment]
The PLA one came out perfectly too, I'm using all the stock settings in the Generic PLA profile

**Comment by sn4k3** [comment]
With stock speeds right? 
Then something is wrong with filament, do you have other pet brand? Humidity can ruin a spool

**Comment by NovaViper** [comment]
I do have other brands, but they all have had the same issue

**Comment by sn4k3** [comment]
Well if problem presists on PET the best bet is test the max MVS your printer steup support. a good way to set that is print with stock profiles. At second layer when problem comes start slowing down the printer speed using the knob (FR) up you see a good line pattern. Then look at FR percentage, lets say it's 75%. Pick stock MVS and multiply by 0.75, eg: 8*0.75 = 6
Thats the way i pick the real max speeds, but again, max everything is not a general rule for everyone, a better extruder can extrude more, depend on each one setup

**Comment by NovaViper** [comment]
Ya think I should also use completely stock filament settings from the Generic PET profile?

**Comment by sn4k3** [comment]
To get your limit yes, and when found create or modify the profile with your value

**Comment by NovaViper** [comment]
I just noticed that the infills are *really* high 
![image](https://user-images.githubusercontent.com/7191115/62988561-772e8a80-be0a-11e9-9308-97ce5cf60b4d.png)

**Comment by NovaViper** [comment]
It's not ripping up layers but it still looks a bit rough 
![image](https://user-images.githubusercontent.com/7191115/62989330-2c624200-be0d-11e9-9201-a6bba1b1f4ca.png)

**Comment by sn4k3** [comment]
> I just noticed that the infills are _really_ high with all stock settings

All settings print at same MVS on infills, speed is a illusion, printing at 40mm/s can be slower than a 20mm/s on other setup, what matter is the Volumetric speed (MVS). So all profiles are boosting infill and solid infill to max. capability. Top and bottom infill are always slower to get a better finish.

Find your best infill speed and use that as reference

**Comment by NovaViper** [comment]
Just finished the stock settings print and it got better when I slowed it down to 70%,  but then for some reason the top infill got blobs in it

**Comment by NovaViper** [comment]
![image](https://user-images.githubusercontent.com/7191115/62989706-c2e33300-be0e-11e9-909b-4c44eb6e9656.png)

**Comment by sn4k3** [comment]
> Just finished the stock settings print and it got better when I slowed it down to 70%, but then for some reason the top infill got blobs in it

Try 60%, then 50% keep testing up to get the perfect look

**Comment by sn4k3** [comment]
What mods you have on your printer? Complete setup? As i see is not stock stock

**Comment by NovaViper** [comment]
The bed is just a plain glass pane I got from Home Depot coated with sugar water, the hotend is actually still the same, except I have mounted my extruder to be directly ontop of the hotend (hence it's direct drive now) and the fan shroud is the Petsfang Bullseye

**Comment by sn4k3** [comment]
Ok then you should calibrate your extruder.
Mark 20cm with a pen on filament, using terminal or LCD extrude 100mm. When it stop check if mark hit at 10cm on the ruller. If no you need calibrate your e-steps.
Also as you have direct drive how much retraction you set on extruder?

**Comment by NovaViper** [comment]
I used to have 1.8mm and 70mm/s for the retraction; when doing the tests, I started using 0.8mm and 35mm/s

**Comment by NovaViper** [comment]
Also how do I calibrate e steps on a direct drive extruder?

**Comment by sn4k3** [comment]
> I used to have 1.8mm and 70mm/s for the retraction; when doing the tests, I started using 0.8mm and 35mm/s

Thats seens ok as start point.

> Also how do I calibrate e steps on a direct drive extruder?

With the method i said before, marking, extruding and verify extruded lenght

**Comment by NovaViper** [comment]
The e steps are fine, I marked 120 and told to extrude 100, and 100mm got extruded

**Comment by sn4k3** [comment]
Ok, one more check: with steppers enabled (Holding) try to pull fillament by hand to see if gear rotate, it shall not rotate. If filament gets out mean gear grub is lose

**Comment by NovaViper** [comment]
I can't get it to budge at all

**Comment by sn4k3** [comment]
> I can't get it to budge at all

Well i'm out of possibilities, i guess you have to decrease speed for PET go with it.
As last check, go slicer and see if nozzle size is correctly set, as extrusions width on advanced (should be 0.45mm)

**Comment by NovaViper** [comment]
Welp! I just I may have discovered what our culprit is! So the weather in my area has been going nuts lately (with it being abnormally hot and because it's Louisiana, the humidity is quite high) and my main air conditioning unit breaking due to the extreme heat, the humidity in the air must have gotten high enough to actually affect the prints. So I went today and let my window air unit run for the majority of the day. I just ran the print and the layers came out perfectly

**Comment by sn4k3** [comment]
Humidity ruin pet spools, if you have that issue better build a spools dehumidifier. Or cook it at 50°c for day

**Comment by NovaViper** [comment]
Ok I think my PETG doesn't like the new temp settings, mid way in printing out this case, I notice this MASSIVE clump of filament stuck on the nozzle and it literally jacked the entire print up

**Comment by NovaViper** [comment]
![image](https://user-images.githubusercontent.com/7191115/63070678-d1e6e580-bee1-11e9-92a8-fea31d1b054c.png)

**Comment by Zviki68** [comment]
What's your nozzle temperature?

**Comment by NovaViper** [comment]
> What's your nozzle temperature? And what slicer you are using?

240 and Prusa Slicer, I'm using all of the stock filament profile settings that's for the Generic PETG filament

**Comment by NovaViper** [comment]
Hey im going to close this! I switched to a TriangleLabs V6 and my printer's being doing really well with the infills and PETG! Thanks for making the profile!

**Comment by sn4k3** [comment]
Most likely a extruder problem before.

**Comment by NovaViper** [comment]
@sn4k3 The oddest thing is that im actually still using the stock extruder, and the printer prints perfectly now with PETG, haven't experienced the same issue since switching

**Comment by sn4k3** [comment]
Some bad tune, better this way
