### ISSUE TITLE
Alternative Path for Settings

### ISSUE THREAD

**Issue by VollmerMarcel** [sn4k3/Ender3#2]
In the 4th step of the installation procedure instead of the path "C:\Users\Public\Documents\Prusa3D\Slic3r settings xxxx" I needed to save it in "C:\Users\<User Name>\AppData\Roaming\Slic3rPE" you may want to add this since it could be hard to find for some users.

**Comment by sn4k3** [comment]
I know about that, but i forgot to fix here.
New version now use a different path for profiles
