### ISSUE TITLE
Insane high acceleration

### ISSUE THREAD

**Issue by Laess3r** [sn4k3/Ender3#21]
Hy!
Why is the acceleration set to 9000mm/sec? The ender 3 default is 500mm/s ;-)
My prints suffer from ringing in both x and y axis with this profile.

Best regards

**Comment by sn4k3** [comment]
You using Ender3 stock?
Check if you have last commit, that was fixed some commits ago

**Comment by Laess3r** [comment]
Hy! Thanks for you reply! Yes, Stock Ender 3 Printer profile. 
You are right, in your current version the accel values seem to be much better! Thank you :-)

**Comment by sn4k3** [comment]
Good, check repository from time a time. I may commit new improvements.
