### ISSUE TITLE
Issue with install on mac using Prusaslicer 2.2.0+

### ISSUE THREAD

**Issue by juan9999** [sn4k3/Ender3#28]
Thanks so much for your work on this!

If I go through the config, and select the beta creality driver, and I exit, then copy the required files, I get an error on startup.

I worked around it by deleting/reinstall and choosing a MK3 printer and creality beta (and removing MK3 later) and it works (plus I get the ender logo on the bed). I then select your printer configurations.

Unfortunately, despite doing that, most of your filaments do not appear (only 4 do).

Any tips?

Thanks!

**Comment by sn4k3** [comment]
Hi, read this: https://github.com/sn4k3/Ender3/issues/26#issuecomment-607474282
