### ISSUE TITLE
getting files into slicer

### ISSUE THREAD

**Issue by lumpy1965** [sn4k3/Ender3#31]
i have copied the files across to the correct subfolders ("printer", "filament", "print") in windows, C:\Users\XXXXX\AppData\Roaming\PrusaSlicer but they don't show up in the drop down box in the program. what am i doing wrong?

**Comment by sn4k3** [comment]
Have you followed instructions? You need do exactly what is told on readme

**Comment by lumpy1965** [comment]
yes i was, 3 or 4 times.
ended up uninstalling Prusa and purging the registry, re-installing from scratch, then tried copying the folders again.
all good now
thanks
