### ISSUE TITLE
[QUESTION] Why no 0.4 nozzle profile for Direct Drive?

### ISSUE THREAD

**Issue by MiniNinja1** [sn4k3/Ender3#32]
I'm curious why you don't have profiles for a direct drive with a 0.4 nozzle. It's a common nozzle size.

I already made one myself based on some of your settings and it's been printing fine. I just wanna know your thoughts!

**Comment by sn4k3** [comment]
Most of profiles were made based on my usages or on requests.
Do a 0.4mm nozzle for DD is very easy, just copy stock profile and change retraction

**Comment by MiniNinja1** [comment]
How about other nozzle sizes besides the one you've given? Do I simply change _Nozzle diameter_ and _Max/Min Layer height limits_?

**Comment by sn4k3** [comment]
If i have that nozzle size configured and you just want convert Bowden to DD then Yes.
If not and let's say you want configure a 0.5mm nozzle, then no and you need to create each print profile with correct extrusion widths and calculate max speeds given the set extrusion

**Comment by MiniNinja1** [comment]
Okay, I see what you mean. I think I'll stick with my 0.4 nozzle for now and do the necessary adjustments. Thanks!

**Comment by o5** [comment]
I've upgraded my Ender 3 PRO by this [guide](https://www.3dpedie.cz/en/inspirations/octoender_by_kiron). I used your profile for stock Ender before but now I'm looking for DD with 0.4mm Nozle and P.I.N.D.A. I started a new profile based on your DD 0.6mm Nozle (no Volcano). Any tips from you? :) 

I changed: Max print height, Commented out G-CODE for BLTouch, Nozzle diameter, Set Retraction length to 1.5mm and speed to 120mm/s. 

I can prepare PR if you are open to add a new profile.

**Comment by sn4k3** [comment]
Direct drive with 0.4mm nozzle you can clone stock ender bltouch and change the the Retraction length and speed, everything will be the same, also adapt the start gcode for the probe that you are using.
Remove PRINTER_HAS_BOWDEN and add PRINTER_HAS_DIRECT_DRIVE on printer notes.
As addition if you are using linear advance, set a model ex: PRINTER_FULLMODEL_ENDER3_DD_04
