### ISSUE TITLE
[QUESTION] There is no stock 0.4 nozzle "print" profile

### ISSUE THREAD

**Issue by rufik** [sn4k3/Ender3#33]
Do I see right there is no "print settings" profile for stock 0.4 nozzle?

**Comment by sn4k3** [comment]
There are, are you with any beta PrusaSlicer version?

**Comment by rufik** [comment]
I'm using PrusaSlicer 2.2.0, so no bete here. When I go into `PrusaSlicer/print` folder there are print profiles for 0.40 nozzle like that:
![image](https://user-images.githubusercontent.com/425558/102590198-7e595d00-4110-11eb-865c-c9b0adee5a8b.png)

Which one is for stock hotend? I can see only for MK3 Volcano ones...

**Comment by pahowes** [comment]
If you're looking in the `PrusaSlicer/print` folder under your user profile, you'll see only those you added manually. The first number is the layer height, not the nozzle size. The second number `0.6 nozzle MK3 Volcano` would refer to an E3D Volcano hot-end with a 0.6 mm nozzle.

The factory profiles are found in the application directory as `profiles/PrusaResearch.ini`. They're all lumped together in that file.

**Comment by sn4k3** [comment]
https://github.com/sn4k3/Ender3/tree/master/PrusaSlicer/print

Stock nozzle files ends with: Ender3.ini
