### ISSUE TITLE
[QUESTION] No PLA filaments show compatible for stock Ender 3?

### ISSUE THREAD

**Issue by jwvanderbeck** [sn4k3/Ender3#34]
Starting from scratch, I installed the latest PrusaSlicer and launched it.  In the configuration wizard I selected a bunch of PLA filament profiles, just basic ones like AmazonBasics, Hatchbox, eSiun, etc.  Next I copied the profiles for this project over and re-launched.

When selecting the Ender 3 Stock none of the PLA filaments will be available, as they all are seen as incompatible.

**Comment by sn4k3** [comment]
Yes, they now have filaments per brand, so that are only for prusa and require flags on printer like PRINTER_VENDOR_PRUSA3D and model mk3 defined.
Just clone my generics and tune from there, or select prusa mk3 clone filament you want and remove conditions to open to all printers
