### ISSUE TITLE
[QUESTION] Direct Drive for 0.4 Nozzle profile

### ISSUE THREAD

**Issue by NovaViper** [sn4k3/Ender3#36]
Hey, I'm wondering if you could make a profile for 0.4 nozzles with direct drive

**Comment by sn4k3** [comment]
It's easy to do:

1. Clone "Creality Ender-3 Stock" profile
2. Change retraction settings to:
![image](https://user-images.githubusercontent.com/113281/116827878-63edc080-ab93-11eb-8ca2-4bd1f7d0c95c.png)

**Comment by NovaViper** [comment]
Ah cool. Thanks for the info! Uh... how do I go and get the filament profiles for the machine?

**Comment by sn4k3** [comment]
You can get them from Official creality filaments on PrusaSlicer, you just need to go to PrusaSlicer Wizard and select Ender3 Printer and it filaments and i think it will show up

**Comment by NovaViper** [comment]
Ah ok, thanks!

**Comment by Moxie1776** [comment]
Be careful with those settings, sometimes with length that hi it can cause your hotend to clog. Speed can be adjusted up too, I would play with those settings. You may want to try zlift starting at .2.

**Comment by sn4k3** [comment]
0.8mm is not that high. My settings are for 3ed setup similar to prusa, but of course there are no universal setting, adjust if needed

**Comment by Moxie1776** [comment]
> 0.8mm is not that high. My settings are for v6 e3d setup similar to prusa, but of course there are no universal setting, adjust if needed

If I go past .6 my all metal microswiss clogs...

**Comment by NovaViper** [comment]
> > 0.8mm is not that high. My settings are for v6 e3d setup similar to prusa, but of course there are no universal setting, adjust if needed
> 
> If I go past .6 my all metal microswiss clogs...

I actually have a V6 and BMG (both are clones) setup with the BMG directly connected to the V6 and dual 5015 fans. The retraction length and speed is actually pretty normal for a V6, anything above 1mm is too much.
