### ISSUE TITLE
ColorMe3D PETG settings

### ISSUE THREAD

**Issue by NovaViper** [sn4k3/Ender3#7]
Hey guys! I'm very new to Slic3r and I would like to know if you guys could create a profile for the ColorMe3D PETG filaments, such as the ones I currently have below:

https://www.amazon.com/gp/product/B07L5V9LP7/ref=ppx_yo_dt_b_asin_title_o03__o00_s00?ie=UTF8&psc=1

https://www.amazon.com/gp/product/B07LB6RXDR/ref=ppx_yo_dt_b_asin_title_o02__o00_s00?ie=UTF8&psc=1

I would really appreciate the addition :D

**Comment by sn4k3** [comment]
Do a blind profile will be inaccurate. Best is try with the real thing.
They say Hotend 235 and BED TEMP at 30, PETG need more temperature to bed to stick well so i recommend you try higher value like GENERIC PETG profile or from 70 to 90ºc. 
After do can do a temperature tower from 210 to 240ºc and see which is better.
With that you will have your profile correct.
PS: Duplicate PETG profile and fine tune it
